# VSCode: zainstalować https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# PhpStorm: obsługa plików .rest jest wbudowana

###
GET http://localhost:8000/api/countries
Accept: application/json

###
OPTIONS http://localhost:8000/api/countries

###
OPTIONS http://localhost:8000/api/countries/1

###
GET http://localhost:8000/api/countries/1
Accept: application/json

###
POST http://localhost:8000/api/countries
Accept: application/json
content-type: application/json

{
    "name": "Czechy",
    "code": "CZ",
    "currency": "korona",
    "area": 78868,
    "language": "czeski"
}

###
POST http://localhost:8000/api/countries
Accept: application/json
content-type: application/json

{
    "name": "Republika Madagaskaru",
    "code": "MG",
    "currency": "ariary",
    "area": null,
    "language": "malgaski"
}

###
PUT http://localhost:8000/api/countries/7
Accept: application/json
content-type: application/json

{
    "name": "Czechy",
    "code": "CZ",
    "currency": "k.czeska",
    "area": 78868,
    "language": "czeski"
}

###
DELETE http://localhost:8000/api/countries/8
Accept: application/json
